### ISSUE TITLE
Utilize schema inheritance

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/rocc-schemas#60]
As I was working through the `User` schema, I noticed that half of the properties I wanted to add were already defined in the `Person` schema.  So, rather than describe the properties again, I made use of [OpenAPI's inheritance feature](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/), `allOf`.

This got me thinking that we could probably apply the same approach to our other entities.  For instance:

- `PersonCreateResponse` describes the `personId` property
- `PersonCreateRequest` describes the `firstName`, `lastName`, `email`, and `organizations` properties
- `Person` describes all the properties listed above

I played around with the schemas a bit and made the following changes to `Person.yaml`:

```
type: object
description: A person
allOf:
  - $ref: PersonCreateResponse.yaml
  - $ref: PersonCreateRequest.yaml
```

and everything still works as expected.

@tschaffter , what are your thoughts on doing this sort of refactor? It would make maintenance a bit easier, e.g. if we wanted to update the `personId` example, we would only need to update `PersonCreateResponse` rather than both that schema and `Person`.

**Comment by tschaffter** [comment]
I'm also using this inheritance mechanism in the NLP Sandbox schemas. Below is how I extend the schema `TextAnnotation` to define the `TextDateAnnotation`:

```
type: object
description: A date annotation in a text
allOf:
  - $ref: TextAnnotation.yaml
  - type: object
    properties:
      dateFormat:
        description: Date format (ISO 8601)
        type: string
        example: "MM/DD/YYYY"
example:
  start: 42
  length: 10
  text: 10/26/2020
  dateFormat: "MM/DD/YYYY"
```

Here is a couple of notes:

- When build the combined specification, the section `example` of `TextAnnotation` is not inherited, which is why the example shown above specifies value for properties from `TextAnnotation`
- Here are a few notes about the Python-Flask implementation generated by `openapi-generator`
  - In the above example, I extend `TextAnnotation` with an unnamed object. This unamed object will be named `TextDateAnnotation_allOf` in the [combined spec](https://github.com/nlpsandbox/date-annotator-example/blob/b27aca2d0acbb38549dd2092106dbaacb9974a01/server/openapi_server/openapi/openapi.yaml#L163). These `_allOf` objects "polute" the documentation and the codebase of the server, especially the section that list all the models of the API. I'm still pondering if I want to use a named object instead, but this does not solve the issue of model pollution, the `_allOf` models will just be renamed with a potentially more descriptive name. By pollution I mean that these schema are usually not meant to be used on their own and so should ideally not be exposed to the user in the doc.
  - At the level of the implementation (Python-Flask), the model TextDateAnnotation is a full implementation and do not make used of Python object inheritance to reuse TextAnnotation. This also means that the object like `_all_of.py` can be removed manually. In at least one of the NLP services, I configured the `openapi-generator` to not create `_all_of.py` files. However the generator will still reference these files in other files, so have I have to remove manually all `import` of such files. This cleans up a bit the codebase.

Back to your example:

```
type: object
description: A person
allOf:
  - $ref: PersonCreateResponse.yaml
  - $ref: PersonCreateRequest.yaml
```

This is an interesting approach and probably compatible with the following notes that look at how `Person` can be inherited by other schemas (e.g. `User`):

Considering the `User` schema that we are adding, we could use inheritance for the following schema:

- `User` extends `Person`
- `UserCreateRequest` extends `PersonCreateRequest`

The Responses having a single property specific to a schema (e.g. `personId`, `userId`), there should be no need to use inheritance to create them.

One tiny problem with the " `User` extends `Person`" is that we may not want to have the property `Person.personId` being inherited by `User`. Instead, we could have `User` extends `PersonCreateRequest`.

I think that this should work! Do you see other edge cases that may have been missed?

**Comment by vpchung** [comment]
>One tiny problem with the " User extends Person" is that we may not want to have the property Person.personId being inherited by User. Instead, we could have User extends PersonCreateRequest.

Great minds think alike -- that's exactly what I did for `User`! e.g.

```
type: object
description: A user of the portal
allOf:
  - $ref: PersonCreateRequest.yaml
  - type: object
    properties:
      username:
        $ref: ../parameters/Username.yaml
...
```

I'll think about the schemas a bit more, and will let you know what I come up with as the final approach.  I just wanted to check in first to see whether you agree inheritance would be a plausible thing to pursue.
